name: flutter_learning

description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  # api
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  uuid: ^4.4.0
  # core api
  auto_route: ^8.1.3
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  hooks_riverpod: ^2.5.1
  injectable: ^2.4.2
  json_annotation: ^4.9.0
  kt_dart: ^1.1.0
  riverpod_annotation: ^2.3.5
  # ui
  auto_size_text: ^3.0.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.3
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12

dependency_overrides:
  meta: ^1.12.0

flutter:
  uses-material-design: true
  assets:
    - path: assets/images/
      flavors:
        - dev
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/opensans/OpenSans-Regular.ttf
          style: normal
        - asset: fonts/opensans/OpenSans-Italic.ttf
          style: italic
        - asset: fonts/opensans/OpenSans-Bold.ttf
          weight: 800
